### ISSUE TITLE
High gain mode and force sensor 

### ISSUE THREAD

**Issue by olivier-stasse** [fkanehiro/openhrp3#119]
Dear all,
Starting from the springJoint.xml example I tried to have a humanoid robot
with high gain and bush joints at the ankles.
The simulation is working fine, but the sensor values are almost twice
the weight of the robot.

Do you have any idea why ?
As far as I understood springJoint is having only Torque control joint and thus is using ForwardDynamicsABM.cpp. When one is using High gain and Torque control joints OpenHRP is using ForwardDynamicsCBM.cpp. 

Best Regards,
Olivier Stasse.

**Comment by fkanehiro** [comment]
Dear @snozawa ,

I think you developed similar example programs (sample robot with shock absorbers).
Have you ever experienced a similar problem?

**Comment by olivier-stasse** [comment]
There is a model of sample robot with shock absorber:
[sample1_bush.wrl](https://github.com/fkanehiro/openhrp3/blob/master/sample/model/sample1_bush.wrl)
but the related project as well as the conf file for the bush values is missing to check the values.

**Comment by olivier-stasse** [comment]
Sorry it appears that I was working with an outdated version, I just found projectGenerator.cpp and the related conf file for sample1_bush.wrl.
I will close the issue and try them.
Sorry for the noise and thanks for your quick reply.

**Comment by snozawa** [comment]
@olivier-stasse 

Sorry for late reply.
You might have already found the related files, FYI, 
https://github.com/fkanehiro/hrpsys-base/tree/master/sample/SampleRobot#samplerobot_stabilizerpy
is an example to use sample1_bush.wrl.
Related conf and xml files are here:
https://github.com/fkanehiro/hrpsys-base/blob/master/sample/SampleRobot/SampleRobot.conf.in
https://github.com/fkanehiro/hrpsys-base/blob/master/sample/SampleRobot/SampleRobot.torque.xml.in
