### ISSUE TITLE
Sample.{pos,vel} がインストールされていない

### ISSUE THREAD

**Issue by k-okada** [fkanehiro/openhrp3#46]
sample/controller/SampleController/etc/
がmake install でコピーされていないみたいです．

**Comment by fkanehiro** [comment]
etcというディレクトリがあればディレクトリごとコピーされるようになっているはずですが、そのように動作していないでしょうか？

**Comment by k-okada** [comment]
なぜかtag 3.1.7にはetcが含まれていないためでした．お騒がさせしました．
https://github.com/fkanehiro/openhrp3/tree/3.1.7/sample/controller/SampleController
