### ISSUE TITLE
Support CURRENT_DIR, PROJECT_DIR in modelloder 

### ISSUE THREAD

**Issue by k-okada** [fkanehiro/openhrp3#55]
c.f https://github.com/fkanehiro/hrpsys-base/blob/master/lib/util/Project.cpp#L145
https://github.com/start-jsk/rtmros_hrp2/pull/115

**Comment by snozawa** [comment]
こちら、どのように使えうことを想定されてますでしょうか。

今ProjectGeneratorでプロジェクトファイル（XML）の他にconfファイル、RobotHardwareのconfファイルがでてきます。
こうすると、一個のコマンド実行で複数ファイルが生成されて、cmakeで依存関係をかいたりが少しややこしくなります。

依存関係がややこしくなくするためには、
ProjectGenerator、ControllerConfGenerator, RobotHardwareConfGeneratorのように
しておくのが良さそうに思いましたが、それ以外の方法として、
こちらのissueが役立つのでは、と思いました。

具体的には、cmakeにこの設定をかいてconfファイルを自動生成したい理由は、
今は多分`model:`のパスをかく必要があるからで、それを`$(CURRENT_DIR)`のようにできると
confファイルでのパスをそのままかくことができ、またconfファイルは自動生成せず普通にコミットされる
ファイルにできるかもしれません。

**Comment by k-okada** [comment]
https://github.com/fkanehiro/hrpsys-base/blob/master/lib/util/Project.cpp#L133
projectファイルはPROJECT_DIRとかCURRENT_DIRがサポートされています．
https://github.com/fkanehiro/openhrp3/blob/master/hrplib/hrpModel/ModelLoaderUtil.h#L33
のurlでこれらの変数をサポートすればいいか，他の場所か，という入れる場所の問題と，
OPENHRP_DIR以外は実用的でない？例えばCURRENT_DIRは
マシンが違うと通用しない？ProjectGeneratorとそろえるならPROJECT_DIR?
という名前の問題があるかな．

**Comment by snozawa** [comment]
この機能・用途が欲しいと思ったことをリストアップしておきます。
- 各ロボット実機のパスを直書きしている箇所がいいかんじになる
- hrpsys_ros_bridgeでconfを自動生成してるけど、パスが解決されるので自動生成がいらなくなる
- hrpsys_ros_bridgeのdevelなどでinstallパスなどをかえてくれる

ができるとうれしいです。
モデル・XMLファイルとconfファイルが全然別なパスにくることも（とくにロボット実機だと）ありますので、
`$(CURRENT_DIR)`と`$(PROJECT_DIR)`だと少し機能として足りないきがします。

例えば環境変数をよむようにするのはいかがでしょうか。

**Comment by fkanehiro** [comment]
これってmodelloaderでCURRENT_DIR等を展開させるということでしょうか？
別プロセスで走っている状況でPROJECT_DIR等をmodelloaderが展開するのは難しそうに思いますがどうでしょうか。


2015年4月20日 15:06 Shunichi Nozawa <notifications@github.com>:

**Comment by k-okada** [comment]
CURRENT_DIRは難しいけど，PROJECT_DIRは可能ではないでしょうか？

--
◉ Kei Okada


2015-04-20 20:05 GMT+09:00 Fumio KANEHIRO <notifications@github.com>:

**Comment by fkanehiro** [comment]
PROJECT_DIRってxmlファイルが置いてあるディレクトリですよね。
それをModelLoaderはどうやって知るんでしょう？

2015年4月20日 20:06 Kei Okada <notifications@github.com>:

**Comment by k-okada** [comment]
あれ？openhrp3のディレクトリだと思っていました．
https://github.com/fkanehiro/hrpsys-base/blob/master/lib/util/Project.cpp#L145
でできているので，できるのかな．と．

--
◉ Kei Okada


2015-04-20 20:09 GMT+09:00 Fumio KANEHIRO <notifications@github.com>:

**Comment by fkanehiro** [comment]
あれ、そういえばそうかな。CURRENT_DIRがxmlのあるディレクトリでしたっけ。


2015年4月20日 20:11 Kei Okada <notifications@github.com>:

**Comment by k-okada** [comment]
http://www.openrtp.jp/openhrp3/3.1.0.beta/jp/install_ubuntu.html
の環境変数のセクションに
export PROJECT_DIR=(OpenHRP3 インストール先)/share/OpenHRP-3.1/sample/project
とありました．これが正でしょうかCURRENT_DIRは
https://openrtp.jp/redmine/issues/1359 で色々議論されているみたいですが，
modelloaderで取り扱うのは危険なのかな．


--
◉ Kei Okada


2015-04-20 20:44 GMT+09:00 Fumio KANEHIRO <notifications@github.com>:

**Comment by fkanehiro** [comment]
はい、PROJECT_DIRはそこなので、pkg-configとか使えばModelLoaderも知ることができますね。
一方でCURRENT_DIRはXMLが置かれてる場所なので、ModelLoaderは知るすべがないですね。

2015年4月22日 1:18 Kei Okada <notifications@github.com>:

**Comment by k-okada** [comment]
#68 で作りました
