### ISSUE TITLE
ゴムブッシュをシミュレートするプログラム

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/openhrp3#58]
ゴムブッシュを使用されてシミュレーションをされてると思いますが、
ゴムブッシュをシミュレートするプログラムはどちらにございますでしょうか。

また、シミュレート方法としては
- VRMLにゴムブッシュに対応した仮想関節を追加する
- projectファイルでは、仮想関節はTorqueにしておく
- 仮想関節でバネ（＋ダンパ？）の挙動となるように、inputが仮想関節の実関節角度でoutputが仮想関節のトルクや力になるようなRTCをはさむ

という方法になってますでしょうか。
よろしくお願いいたします。

**Comment by fkanehiro** [comment]
openhrp3ではカスタマイザという仕組みがあります。
通常のコントローラでゴムブッシュをシミュレートすると遅れが入ってしまいますが、カスタマイザを使えば遅れなしでゴムブッシュの反応をシミュレートできます。

**Comment by snozawa** [comment]
ありがとうございます。
初歩的な質問で恐縮なのですが、カスタマイザ自体のサンプル、チュートリアルはどちらにございますでしょうか。
また、ずばりゴムブッシュ用のカスタマイザサンプルはございますでしょうか。

> 通常のコントローラでゴムブッシュをシミュレートすると遅れが入ってしまいますが、カスタマイザを使えば遅れなしでゴムブッシュの反応をシミュレートできます。

こちらの遅れは、例えばコントローラでゴムブッシュの挙動をシミュレートしようとして、
- （ゴムブッシュ仮想関節の）エンコーダ値とバネ定数からトルクを計算
- トルクを出力

としたときに、１制御周期分遅れるといったものでしょうか。
よろしくお願いいたします。

**Comment by fkanehiro** [comment]
>
> 初歩的な質問で恐縮なのですが、カスタマイザ自体のサンプル、チュートリアルはどちらにございますでしょうか。
>

https://github.com/fkanehiro/openhrp3/blob/master/sample/project/SpringJoint.xml
を参考にして下さい。

> こちらの遅れは、例えばコントローラでゴムブッシュの挙動をシミュレートしようとして、
>
>    - （ゴムブッシュ仮想関節の）エンコーダ値とバネ定数からトルクを計算
>    - トルクを出力
>
> としたときに、１制御周期分遅れるといったものでしょうか。
> よろしくお願いいたします。
>
はい、その通りです。
通常のコントローラでは計算したトルクは次の周期で適用されますが、カスタマイザでは同一の周期で計算したトルクを適用できます。

**Comment by snozawa** [comment]
ありがとうございます。
こちらの方法をロボットの足首ゴムブッシュにしようとするには、それ専用のcustomizerを作成して読み込む必要があるということになりますでしょうか。

**Comment by fkanehiro** [comment]
はい、そうなりますね。

2015年6月14日 20:51 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
ちなみに、シミュレーション時のプロジェクトファイルの設定で、
EULERとRUNGEKUTTAはどちらにされてますか？

**Comment by fkanehiro** [comment]
RUNGEKUTTAです。

**Comment by snozawa** [comment]
ありがとうございます。

**Comment by snozawa** [comment]
こちら一旦閉じたいとおもいます。
ありがとうございました。

**Comment by snozawa** [comment]
http://www.openrtp.jp/openhrp3/jp/springJoint.html
に関してですが、openhrp3本体のインストール先にコピーする以外の方法で
パスを通すようなことは可能でしょうか。
現在こちらの環境ではapt-getでのインストールもあり
「OpenHRP-3.1/customizer/以下にコピーする」がルート権限が必要な作業となるのではと考えており、
例えばOpenRTMの読みこみパスの指定のようなものは可能でしょうか。

またこの現状custmizer以下にコピーしてしまうと、シミュレーションきどうじに
動力学ライブラリに読み込まれてしまい、*.so(dll)を削除する以外に、
行いたいシミュレーションごとにそれをON・OFFすることができないという理解でよろしいでしょうか。

**Comment by snozawa** [comment]
度々失礼します。
customizerが起動時に読み込む設定・ファイル等はございますでしょうか。
ゴムブッシュを使用するか、するとしたら何自由度のゴムブッシュとするか、といった情報を設定ファイルか何かに記述して、使用時に切り替えることは可能でしょうか。

**Comment by fkanehiro** [comment]
2015年8月19日 1:02 Shunichi Nozawa <notifications@github.com>:

> http://www.openrtp.jp/openhrp3/jp/springJoint.html
> に関してですが、openhrp3本体のインストール先にコピーする以外の方法で
> パスを通すようなことは可能でしょうか。
> 現在こちらの環境ではapt-getでのインストールもあり
> 「OpenHRP-3.1/customizer/以下にコピーする」がルート権限が必要な作業となるのではと考えており、
> 例えばOpenRTMの読みこみパスの指定のようなものは可能でしょうか。
>
HRPMODEL_CUSTOMIZER_PATHという環境変数で指定可能のようです。
https://github.com/fkanehiro/openhrp3/blob/master/hrplib/hrpModel/BodyCustomizerInterface.cpp#L250


> またこの現状custmizer以下にコピーしてしまうと、シミュレーションきどうじに
> 動力学ライブラリに読み込まれてしまい、*.so(dll)を削除する以外に、
> 行いたいシミュレーションごとにそれをON・OFFすることができないという理解でよろしいでしょうか。
>

そうですね。

**Comment by fkanehiro** [comment]
標準的な方法は用意されていないようですので、カスタマイザの実装時に好きなファイルを読む、ということになりそうです。

2015年8月19日 2:22 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
ありがとうございます。
PATH指定方法わかりました。
ファイル読み込み、起動の切り替え等もありがとうございます。

ちなみに
http://www.openrtp.jp/openhrp3/jp/springJoint.html
の記述を更新するには何か権限が必要でしょうか。

**Comment by fkanehiro** [comment]
OpenHRP3のHPはソースが古いsvnに置いたままでgithubには移行してないので、移行しないといけない、というのと移行してもHPの更新は手動、という状況です。
ちょっとお待ちください。

2015年8月19日 12:57 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
ありがとうございます。
マニュアル更新自体は全く急ぎではございませんので、お手すきのときでかまいません。

**Comment by snozawa** [comment]
https://github.com/fkanehiro/openhrp3/pull/71
で解決しました。

**Comment by fkanehiro** [comment]
fkanehiro/openhrp3-doc
にHPのソースをおき、生成されたページを
fkanehiro.github.io/openhrp3
で参照できるようにしました。
ページの改善にご協力頂けるようでしたら是非よろしくお願いします。

2015年8月21日 17:43 Shunichi Nozawa <notifications@github.com>:

**Comment by fkanehiro** [comment]
fkanehiro.github.io/openhrp3-doc
でしたね。念のため。

2015年9月3日 16:05 Fumio Kanehiro <fkanehiro@gmail.com>:

**Comment by snozawa** [comment]
早速のご対応誠にありがとうございます。
こちら参照等させていただきたく存じます。

**Comment by snozawa** [comment]
https://github.com/fkanehiro/openhrp3-doc/pull/1
に追記してみました。

ところで
fkanehiro.github.io/openhrp3-doc
のページ自体は見ることができるのですが、どこかにリンクがはられていたりしますでしょうか。
また、これまでの
http://www.openrtp.jp/openhrp3/jp/
との関係はどうなりますでしょうか。
おそらくopenrtpのほうからgithubioにとんでいくようになるとよさそうにおもいまsした。
