### ISSUE TITLE
openhrp3ページのドキュメント

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/openhrp3#61]
projectGeneratorなどの説明をかこう or かいてもらおうとしていたのですが、
どちらにかいていくのが良いでしょうか。
hrpsys-baseのようにdoxygenがございますでしょうか。
もしくは、REAME.mdか、
http://www.openrtp.jp/openhrp3/jp/users_manual_3_0.html
になりますでしょうか。
ユーザーズマニュアルの場合、どのようにして編集すればよろしいでしょうか。

**Comment by eisoku9618** [comment]
projectGeneratorのREADME.mdは

https://github.com/fkanehiro/openhrp3/tree/master/server/ModelLoader

に以前追加しました，という話を @snozawa さんとオフラインでお話しして，

https://github.com/fkanehiro/openhrp3/pull/62

にてオプション説明と使い方サンプルを追加しました．

**Comment by eisoku9618** [comment]
roswiki も変更して，上記のREADME.mdに誘導するようにしました．

http://wiki.ros.org/rtmros_common/Tutorials/AddRobotsEnvironmentsHrpsysSimulator#Generate_project_file

**Comment by snozawa** [comment]
ありがとうございます。
