### ISSUE TITLE
分岐のあるマニピュレータ・ベースリンク成分のあるヤコビアン計算

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/openhrp3#65]
分岐のあるマニピュレータ、ベースリンクの６自由度成分のあるヤコビアン計算するプログラムは
openhrp3にありますでしょうか。
JointPathは、計算では分岐のないヤコビアン計算のみになりますでしょうか。
よろしくお願いいたします。

**Comment by fkanehiro** [comment]
https://github.com/fkanehiro/openhrp3/blob/master/hrplib/hrpModel/JointPath.cpp#L128
を見ると回転、直動関節で構成されるシリアルリンクのみの対応のようですね。

**Comment by snozawa** [comment]
ありがとうございます。

こちらの
> 分岐のあるマニピュレータ、ベースリンクの６自由度成分のあるヤコビアン計算するプログラム

の部分は、downstreamのほうには存在していると思いますが、
openhrp3のほうに追加される予定はございますでしょうか。
よろしくお願いいたします。

**Comment by fkanehiro** [comment]
予定は、すいません、ありません。
コードは確かに存在しているのですが、そのままopenhrp3に入れられる、という状況でもなく整理が必要で、なかなかそこまで手がまわらない、という状況です。

2015年8月19日 12:13 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
こちら承知しました。
色々とありがとうございました。
