### ISSUE TITLE
ロボットと環境・物体モデルとの間で干渉がある場合の位置・力などの取得方法

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/openhrp3#83]
ロボットと環境・物体モデルとの間で干渉がある場合の位置・力などを
openhrp3もしくはchoreonoidで取得する方法はございますでしょうか。

ロボットを転倒させてどこにどれくらいの力がかかるかをシミュレーションしようと思っております。
内部的にはもちろん力・位置が取得できるものとは思いますが、
ユーザレベルのところで何かAPI等ございますでしょうか。
できれば、hrpsys-baseのDataLoggerのようなものでログとして保存できるとうれしいです。

また少し話はそれますが、こういったシミュレーションを行う場合は
関節がトルクモードで駆動されていればそれなりの値が取得できると考えて差し支えありませんでしょうか。
例えば、ゴムブッシュのような要素をどこかに入れたほうが適切な結果になるといったことはございますでしょうか。

初歩的な質問ではありますが、よろしくお願いいたします。

**Comment by fkanehiro** [comment]
OpenHRP3だとコントローラブリッジのCONSTRAINT_FORCEというタイプでデータを取り出せますね。
ChoreonoidだとBodyRTCのCONSTRAINT_FORCEで取り出せそうです。
残念ながらhrpsys-baseでは手抜きでそこは実装していないようです。

2015年10月15日 20:21 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
ご回答いただきありがとうございます．
こちらのCONSTRAQINT_FORCEについて，調べてみます．

シミュレーション自体はトルクモードであれば問題はとくにございませんでしょうか．

**Comment by fkanehiro** [comment]
そのあたりあまり真面目に確認したことはないのですが、関節がトルク制御の方がより現実に近づくとは思います。
あとは基本的には剛体の完全非弾性衝突なのでそれなりでしょうか。

2015年10月15日 20:50 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
わかりました。
ありがとうございます。

**Comment by snozawa** [comment]
こちらchoreonoidで試せそうですので、一旦closeします。
ありがとうございました。
