### ISSUE TITLE
openhrp3の外のプログラムでCORBA通信越しにModelLoaderからmodelをloadする方法でなくmodelをloadする方法

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/openhrp3#87]
openhrp3の外のプログラムで(具体的にはhrpsys-base)、CORBA通信越しにModelLoaderからmodelをloadする方法でなく、
https://github.com/fkanehiro/openhrp3/blob/master/server/ModelLoader/projectGenerator.cpp
のようにそのプログラム内で直接loadModelFileして使う方法はありますでしょうか。

**Comment by snozawa** [comment]
用途は、hrpsys-baseのtravisのテストなどで、modelloader等立ち上げずそのプログラム内でモデルをloadしてテストしたりしたい、というものです。

**Comment by fkanehiro** [comment]
標準的な方法は用意していないです。
やるとするとprojectGeneratorがやっているようなことが外部からもできるようにModelLoaderのコードの
一部をライブラリ側に移すのだと思います。

2016年1月8日 12:44 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
わかりました。
いずれにしても、ちょっと作業がいりそうですね。
ありがとうございます。

**Comment by snozawa** [comment]
こちら進めたくなったら再度openします。
ありがとうございました。
