### ISSUE TITLE
required なboostのバージョン

### ISSUE THREAD

**Issue by snozawa** [fkanehiro/openhrp3#88]
必要とされるboostバージョンは1.36
https://github.com/fkanehiro/openhrp3/blob/master/CMakeLists.txt#L120
とかいてありますが、これはどこから起因するものでしょうか。

ちなみに、古いロボット体内環境がboost 1.34で、
```
$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4af4271..c53ffdc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -117,7 +117,7 @@ set(Boost_ADDITIONAL_VERSIONS "1.42" "1.42.0" "1.43" "1.43.0" "1.44" "1.44.0" "1
     endif()
     find_package(Boost 1.35.0 REQUIRED )
   elseif(UNIX)
-    find_package(Boost 1.36.0 REQUIRED COMPONENTS filesystem signals system regex program_options)
+    find_package(Boost 1.34.0 REQUIRED COMPONENTS filesystem signals regex program_options)
     if(NOT Boost_FOUND)
      set(BOOST_ROOT ${BOOST_ROOT} CACHE PATH "set the directory of the boost library")
      message(FATAL_ERROR "Boost cannot be found. Please specify the boost top directory to BOOST_ROOT.")
```
と1.34にして、かつboost_systemもなかったのではずしたところ、ビルド自体は通りました（undefined symbolになるかもしれません）。

**Comment by fkanehiro** [comment]
単に色んなバージョンでのテストをしていないためにOSのバージョンが上がった時にBoostの必要バージョンも一緒に上げたとか、その程度の理由だと思います。
ただ上の変更だと、ご想像通りboost_systemがあるバージョンではundefined symbolになると思います。

**Comment by snozawa** [comment]
```
    find_package(Boost 1.34.0 REQUIRED COMPONENTS filesystem signals system regex program_options)
```
でも通り，downstreamのhrpsys-baseも現状制御系等は動作が確認できてます．
（ちなみにboost_systemがないこと自体はcmakeのwarningでerrorにはならないです．）

おそらく，1.34.0でも動いて，ただしboost_systemがリンクされてないので，
boost_systemがあるものを使うとundefined symbolになるのかもしれません．

1.36.0 => 1.34.0にしてPRしてもよろしいでしょうか．

**Comment by snozawa** [comment]
>  （ちなみにboost_systemがないこと自体はcmakeのwarningでerrorにはならないです．）

すいません，見間違いでした．したがって
> 1.36.0 => 1.34.0にしてPRしてもよろしいでしょうか．

だけでは通りませんでした．

**Comment by snozawa** [comment]
> （ちなみにboost_systemがないこと自体はcmakeのwarningでerrorにはならないです．）

これは
```
    find_package(Boost 1.34.0 COMPONENTS filesystem signals system regex program_options)
```
でREQUIREDを消したときのものでした．

**Comment by snozawa** [comment]
find_packageのREQUIREDを消すとまずいでしょうか？

**Comment by fkanehiro** [comment]
う～ん、どうでしょう。
試しに消してみるというのはあるかもしれませんね。

2016-01-08 21:24 GMT+09:00 Shunichi Nozawa <notifications@github.com>:

**Comment by k-okada** [comment]
https://github.com/fkanehiro/openhrp3/pull/89/files
でどうでしょうか．
http://www.boost.org/doc/libs/1_36_0/
のSystemというところを見ると
```
System
Operating system support, including the diagnostics support that will be part of the C++0x standard library.

Author(s): Beman Dawes
First Release :1.35.0
Standard: 
 Categories: System
```
とあります．

一点，いまはUnixは1.36が必須となっていて，Windowsは1.35になっています．36とした理由がとくになく35でいいんでは，と勝手に思って変更してありますが，根拠はないので間違っているかもしれないです．

**Comment by snozawa** [comment]
今日確認したところ、
https://github.com/fkanehiro/openhrp3/pull/89
で古い環境でもパッチなく動いたと思います。ありがとうございました。
