### ISSUE TITLE
openhrp-export-colladaの使い方

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/openhrp3#91]
@k-okada さん、 @snozawa さん、 @YoheiKakiuchi さん、どなたかopenhrp-export-colladaの-aオプションの使い方を教えていただけないでしょうか。
colladaモデルを生成して、openraveのikfastを試してみたいと考えています。
よろしくお願いします。

**Comment by k-okada** [comment]
https://github.com/start-jsk/rtmros_tutorials/blob/master/hrpsys_ros_bridge_tutorials/CMakeLists.txt#L224
でしょうか．end-coords? gripper?をつけている部分だと思います．
ただ，まずは-aオプションなしでLARM_LINK6_LInk みたいなのが末端リンクだと思って進めるのでいい気がします．

--
◉ Kei Okada


2016-02-08 14:42 GMT+09:00 Fumio KANEHIRO <notifications@github.com>:

**Comment by YoheiKakiuchi** [comment]
追加情報です。

```-a <manipulator_name>,<frame_origin>,<frame_tip>,<px>,<py>,<pz>,<rotX>,<rotY>,<rotZ>,<rotTheta[rad]>,<gripper_joint>,<closing_direction>```

**Comment by fkanehiro** [comment]
情報ありがとうございます。
